# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1_s:
    has_velocity_limits: true
    max_velocity: 3.66519142919
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2_l:
    has_velocity_limits: true
    max_velocity: 3.66519142919
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3_u:
    has_velocity_limits: true
    max_velocity: 4.62512251778
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4_r:
    has_velocity_limits: true
    max_velocity: 7.33038285838
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5_b:
    has_velocity_limits: true
    max_velocity: 7.33038285838
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6_t:
    has_velocity_limits: true
    max_velocity: 15.4461638801
    has_acceleration_limits: false
    max_acceleration: 0